GENOM_FA: gs://seq-resources/UCSC-mm10/mm10.fa.gz
BT2_FILES:
  - gs://seq-resources/UCSC-mm10/mm10.1.bt2
  - gs://seq-resources/UCSC-mm10/mm10.2.bt2
  - gs://seq-resources/UCSC-mm10/mm10.3.bt2
  - gs://seq-resources/UCSC-mm10/mm10.4.bt2
  - gs://seq-resources/UCSC-mm10/mm10.rev.1.bt2
  - gs://seq-resources/UCSC-mm10/mm10.rev.2.bt2

BT2_IDX_PFX: seq-resources/UCSC-mm10/mm10
TOPHAT2_LIB_TYPE: fr-firststrand


samples:
  AD004:
    fastq:
      r1:
        - fastq/AD004_GTCCGC_L003_R1_001.fastq.gz
        - fastq/AD004_GTCCGC_L004_R1_001.fastq.gz
      r2:
        - fastq/AD004_GTCCGC_L003_R2_001.fastq.gz
        - fastq/AD004_GTCCGC_L004_R2_001.fastq.gz
  AD005:
    fastq:
      r1:
        - fastq/AD005_GTGAAA_L003_R1_001.fastq.gz
        - fastq/AD005_GTGAAA_L004_R1_001.fastq.gz
      r2:
        - fastq/AD005_GTGAAA_L003_R2_001.fastq.gz
        - fastq/AD005_GTGAAA_L004_R2_001.fastq.gz
  AD006:
    fastq:
      r1:
        - fastq/AD006_GTGGCC_L003_R1_001.fastq.gz
        - fastq/AD006_GTGGCC_L004_R1_001.fastq.gz
      r2:
        - fastq/AD006_GTGGCC_L003_R2_001.fastq.gz
        - fastq/AD006_GTGGCC_L004_R2_001.fastq.gz
  AD007:
    fastq:
      r1:
        - fastq/AD007_GTTTCG_L003_R1_001.fastq.gz
        - fastq/AD007_GTTTCG_L004_R1_001.fastq.gz
      r2:
        - fastq/AD007_GTTTCG_L003_R2_001.fastq.gz
        - fastq/AD007_GTTTCG_L004_R2_001.fastq.gz
  AD008:
    fastq:
      r1:
        - fastq/AD008_CGTACG_L003_R1_001.fastq.gz
        - fastq/AD008_CGTACG_L004_R1_001.fastq.gz
      r2:
        - fastq/AD008_CGTACG_L003_R2_001.fastq.gz
        - fastq/AD008_CGTACG_L004_R2_001.fastq.gz
  AD009:
    fastq:
      r1:
        - fastq/AD009_GAGTGG_L003_R1_001.fastq.gz
        - fastq/AD009_GAGTGG_L004_R1_001.fastq.gz
      r2:
        - fastq/AD009_GAGTGG_L003_R2_001.fastq.gz
        - fastq/AD009_GAGTGG_L004_R2_001.fastq.gz
